name: Lurker
main: wa.was.Lurker.connectionTracker
version: 0.1
commands:
  ptime:
    description: Get your current player time, or the player time of others. In the case of console, get uptime.
    usage: /ptime (username)
permissions:
    lurker.cmd:
        description: Allows use of /ptime command
        default: true